In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler 
from sklearn.neural_network import MLPClassifier
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier

In [2]:
df = pd.read_csv('Teams-csv.csv')

In [3]:
df

yearID lgID teamID franchID divID  Rank    G  Ghome    W    L  ...   DP  \
0       1910   AL    BOS      BOS   NaN     4  158   80.0   81   72  ...   80   
1       1910   NL    BRO      LAD   NaN     6  156   80.0   64   90  ...  125   
2       1910   NL    BSN      ATL   NaN     8  157   78.0   53  100  ...  137   
3       1910   AL    CHA      CHW   NaN     6  156   79.0   68   85  ...  100   
4       1910   NL    CHN      CHC   NaN     1  154   77.0  104   50  ...  110   
...      ...  ...    ...      ...   ...   ...  ...    ...  ...  ...  ...  ...   
2453    2021   NL    SLN      STL     C     2  162   81.0   90   72  ...  137   
2454    2021   AL    TBA      TBD     E     1  162   81.0  100   62  ...  130   
2455    2021   AL    TEX      TEX     W     5  162   81.0   60  102  ...  146   
2456    2021   AL    TOR      TOR     E     4  162   80.0   91   71  ...  122   
2457    2021   NL    WAS      WSN     E     5  162   81.0   65   97  ...  116   

         FP                  name                              park  \
0     0.954        Boston Red Sox         Huntington Avenue Grounds   
1     0.964     Brooklyn Superbas               Washington Park III   
2     0.954          Boston Doves             South End Grounds III   
3     0.954     Chicago White Sox  South Side Park II/Comiskey Park   
4     0.963          Chicago Cubs                 West Side Park II   
...     ...                   ...                               ...   
2453  0.986   St. Louis Cardinals                 Busch Stadium III   
2454  0.986        Tampa Bay Rays                   Tropicana Field   
2455  0.986         Texas Rangers                  Globe Life Field   
2456  0.984     Toronto Blue Jays                      Sahlen Field   
2457  0.983  Washington Nationals                    Nationals Park   

      attendance  BPF  PPF  teamIDBR  teamIDlahman45  teamIDretro  
0       584619.0  102  101       BOS             BOS          BOS  
1       279321.0   97  100       BRO             BRO          BRO  
2       149027.0  103  109       BSN             BSN          BSN  
3       552084.0   95   95       CHW             CHA          CHA  
4       526152.0   99   95       CHC             CHN          CHN  
...          ...  ...  ...       ...             ...          ...  
2453   2102530.0   92   92       STL             SLN          SLN  
2454    761072.0   92   91       TBR             TBA          TBA  
2455   2110258.0   99  101       TEX             TEX          TEX  
2456    805901.0  102  101       TOR             TOR          TOR  
2457   1465543.0   95   96       WSN             MON          WAS  

[2458 rows x 48 columns]

In [4]:
teams = df.to_numpy()

In [5]:
x = np.delete(teams,13,1)

In [6]:
x = np.delete(x, 5, 1)

In [7]:
x = np.delete(x, 7, 1)

In [8]:
x = np.delete(x, 7, 1)

In [9]:
x

array([[1910, 'AL', 'BOS', ..., 'BOS', 'BOS', 'BOS'],
       [1910, 'NL', 'BRO', ..., 'BRO', 'BRO', 'BRO'],
       [1910, 'NL', 'BSN', ..., 'BSN', 'BSN', 'BSN'],
       ...,
       [2021, 'AL', 'TEX', ..., 'TEX', 'TEX', 'TEX'],
       [2021, 'AL', 'TOR', ..., 'TOR', 'TOR', 'TOR'],
       [2021, 'NL', 'WAS', ..., 'WSN', 'MON', 'WAS']], dtype=object)

In [10]:
xencoded = OneHotEncoder().fit_transform(x)

In [11]:
xencoded

<2458x12284 sparse matrix of type '<class 'numpy.float64'>'
	with 108152 stored elements in Compressed Sparse Row format>

In [12]:
Y = teams[:,13]

In [13]:
teams[0]

array([1910, 'AL', 'BOS', 'BOS', nan, 4, 158, 80.0, 81, 72, nan, nan, 'N',
       'N', 641, 5204, 1350, 175, 87, 43, 430, 719.0, 194, nan, 56.0, nan,
       564, 390, 2.45, 100, 12, 6, 4290, 1236, 30, 414, 670, 309, 80,
       0.954, 'Boston Red Sox', 'Huntington Avenue Grounds', 584619.0,
       102, 101, 'BOS', 'BOS', 'BOS'], dtype=object)

In [14]:
Y

array(['N', 'N', 'N', ..., 'N', 'N', 'N'], dtype=object)

In [15]:
x[1]

array([1910, 'NL', 'BRO', 'LAD', nan, 156, 80.0, nan, nan, 'N', 497, 5125,
       1174, 166, 73, 25, 434, 706.0, 151, nan, 40.0, nan, 623, 484, 3.07,
       103, 15, 5, 4261, 1331, 17, 545, 555, 235, 125, 0.964,
       'Brooklyn Superbas', 'Washington Park III', 279321.0, 97, 100,
       'BRO', 'BRO', 'BRO'], dtype=object)

In [16]:
X_train, X_test, y_train, y_test = train_test_split(xencoded, Y, test_size=0.30, random_state=1)

In [17]:
X_train[0]

<1x12284 sparse matrix of type '<class 'numpy.float64'>'
	with 44 stored elements in Compressed Sparse Row format>

In [18]:
nnmodel = MLPClassifier(random_state=1).fit(X_train, y_train)

In [19]:
nnmodel.score(X_test, y_test)

0.9552845528455285

In [20]:
rfmodel = RandomForestClassifier(max_depth=5, random_state=0).fit(X_train, y_train)

In [21]:
rfmodel.score(X_test, y_test)

0.9566395663956639

In [24]:
features_df=df[['yearID', 'teamID']].copy(deep=True)

In [25]:
fullteamsdf = pd.read_csv('Teams.csv')

In [26]:
fullteamsdf

yearID lgID teamID franchID divID  Rank    G  Ghome    W    L  ...   DP  \
0       1871  NaN    BS1      BNA   NaN     3   31    NaN   20   10  ...   24   
1       1871  NaN    CH1      CNA   NaN     2   28    NaN   19    9  ...   16   
2       1871  NaN    CL1      CFC   NaN     8   29    NaN   10   19  ...   15   
3       1871  NaN    FW1      KEK   NaN     7   19    NaN    7   12  ...    8   
4       1871  NaN    NY2      NNA   NaN     5   33    NaN   16   17  ...   14   
...      ...  ...    ...      ...   ...   ...  ...    ...  ...  ...  ...  ...   
2980    2021   NL    SLN      STL     C     2  162   81.0   90   72  ...  137   
2981    2021   AL    TBA      TBD     E     1  162   81.0  100   62  ...  130   
2982    2021   AL    TEX      TEX     W     5  162   81.0   60  102  ...  146   
2983    2021   AL    TOR      TOR     E     4  162   80.0   91   71  ...  122   
2984    2021   NL    WAS      WSN     E     5  162   81.0   65   97  ...  116   

         FP                     name                          park  \
0     0.834     Boston Red Stockings           South End Grounds I   
1     0.829  Chicago White Stockings       Union Base-Ball Grounds   
2     0.818   Cleveland Forest Citys  National Association Grounds   
3     0.803     Fort Wayne Kekiongas                Hamilton Field   
4     0.840         New York Mutuals      Union Grounds (Brooklyn)   
...     ...                      ...                           ...   
2980  0.986      St. Louis Cardinals             Busch Stadium III   
2981  0.986           Tampa Bay Rays               Tropicana Field   
2982  0.986            Texas Rangers              Globe Life Field   
2983  0.984        Toronto Blue Jays                  Sahlen Field   
2984  0.983     Washington Nationals                Nationals Park   

      attendance  BPF  PPF  teamIDBR  teamIDlahman45  teamIDretro  
0            NaN  103   98       BOS             BS1          BS1  
1            NaN  104  102       CHI             CH1          CH1  
2            NaN   96  100       CLE             CL1          CL1  
3            NaN  101  107       KEK             FW1          FW1  
4            NaN   90   88       NYU             NY2          NY2  
...          ...  ...  ...       ...             ...          ...  
2980   2102530.0   92   92       STL             SLN          SLN  
2981    761072.0   92   91       TBR             TBA          TBA  
2982   2110258.0   99  101       TEX             TEX          TEX  
2983    805901.0  102  101       TOR             TOR          TOR  
2984   1465543.0   95   96       WSN             MON          WAS  

[2985 rows x 48 columns]

In [31]:
def get_win_perc (row):
    year = row['yearID'] - 1
    team = row['teamID']
    filtered_df = fullteamsdf[(fullteamsdf['yearID'] == year) & (fullteamsdf['teamID'] == team)]
    if filtered_df.empty:
        return 'NaN'
    w = filtered_df.iloc[0, 8]
    l = filtered_df.iloc[0, 9]
    return w / (w + l)

In [29]:
get_win_perc(df.iloc[1])

0.35947712418300654

In [35]:
features_df['prev_year_win_perc'] = features_df.apply (lambda row: get_win_perc(row), axis=1)

In [36]:
features_df

yearID teamID prev_year_win_perc
0       1910    BOS           0.582781
1       1910    BRO           0.359477
2       1910    BSN           0.294118
3       1910    CHA           0.513158
4       1910    CHN           0.679739
...      ...    ...                ...
2453    2021    SLN           0.517241
2454    2021    TBA           0.666667
2455    2021    TEX           0.366667
2456    2021    TOR           0.533333
2457    2021    WAS           0.433333

[2458 rows x 3 columns]

In [39]:
def win_perc (team, year):
    filtered_df = fullteamsdf[(fullteamsdf['yearID'] == year) & (fullteamsdf['teamID'] == team)]
    if filtered_df.empty:
        return 'NaN'
    w = filtered_df.iloc[0, 8]
    l = filtered_df.iloc[0, 9]
    return w / (w + l)
def get_rolling_5_win_perc (row):
    year = row['yearID']
    team = row['teamID']
    year1 = win_perc(team, year - 1)
    year2 = win_perc(team, year - 2)
    year3 = win_perc(team, year - 3)
    year4 = win_perc(team, year - 4)
    year5 = win_perc(team, year - 5)
    if (year1 == 'NaN' or year2 == 'NaN' or year3 == 'NaN' or year3 == 'NaN' or year4 == 'NaN' or year5 == 'NaN'):
        return 'NaN'
    else: 
        return (year1 + year2 + year3 + year4 + year5)/5

In [40]:
features_df['5_year_win_perc'] = features_df.apply (lambda row: get_rolling_5_win_perc(row), axis=1)

In [41]:
features_df

yearID teamID prev_year_win_perc 5_year_win_perc
0       1910    BOS           0.582781        0.459421
1       1910    BRO           0.359477        0.378564
2       1910    BSN           0.294118        0.350155
3       1910    CHA           0.513158        0.577884
4       1910    CHN           0.679739        0.678202
...      ...    ...                ...             ...
2453    2021    SLN           0.517241        0.533078
2454    2021    TBA           0.666667        0.545679
2455    2021    TEX           0.366667        0.465926
2456    2021    TOR           0.533333         0.48321
2457    2021    WAS           0.433333        0.539753

[2458 rows x 4 columns]

In [42]:
fullteamsdf.shape

(2985, 48)